# Generated by Django 4.2 on 2023-04-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=20)),
                ('dayOfWeek', models.IntegerField(choices=[(3, 'THU'), (1, 'TUE'), (2, 'WED'), (0, 'MON'), (5, 'SAT'), (4, 'FRI'), (6, 'SUN')])),
                ('start_time_local', models.DateTimeField()),
                ('end_time_local', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=20)),
                ('timestamp_utc', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StoreTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=20)),
                ('timezone_str', models.CharField(default='America/Chicago', max_length=50)),
            ],
        ),
    ]
