# Generated by Django 4.2 on 2023-04-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_businesshour_dayofweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshour',
            name='dayOfWeek',
            field=models.IntegerField(choices=[(5, 'SAT'), (0, 'MON'), (2, 'WED'), (3, 'THU'), (1, 'TUE'), (6, 'SUN'), (4, 'FRI')]),
        ),
    ]
