# Generated by Django 4.2 on 2023-04-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_businesshour_dayofweek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshour',
            name='dayOfWeek',
            field=models.IntegerField(choices=[(0, 'MON'), (6, 'SUN'), (1, 'TUE'), (3, 'THU'), (5, 'SAT'), (2, 'WED'), (4, 'FRI')]),
        ),
        migrations.AddConstraint(
            model_name='businesshour',
            constraint=models.UniqueConstraint(fields=('store_id', 'dayOfWeek'), name='unique appversion'),
        ),
    ]
