# Generated by Django 4.2 on 2023-04-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_businesshour_dayofweek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshour',
            name='dayOfWeek',
            field=models.IntegerField(choices=[(5, 'SAT'), (3, 'THU'), (6, 'SUN'), (1, 'TUE'), (0, 'MON'), (2, 'WED'), (4, 'FRI')]),
        ),
    ]
