# Generated by Django 4.2 on 2023-04-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_businesshour_dayofweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshour',
            name='dayOfWeek',
            field=models.IntegerField(choices=[(2, 'WED'), (6, 'SUN'), (4, 'FRI'), (1, 'TUE'), (0, 'MON'), (3, 'THU'), (5, 'SAT')]),
        ),
    ]
