# Generated by Django 4.2 on 2023-04-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_businesshour_dayofweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshour',
            name='dayOfWeek',
            field=models.IntegerField(choices=[(1, 'TUE'), (0, 'MON'), (2, 'WED'), (5, 'SAT'), (6, 'SUN'), (3, 'THU'), (4, 'FRI')]),
        ),
    ]
