# Generated by Django 4.2 on 2023-04-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_businesshour_dayofweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshour',
            name='dayOfWeek',
            field=models.IntegerField(choices=[(6, 'SUN'), (0, 'MON'), (3, 'THU'), (1, 'TUE'), (5, 'SAT'), (4, 'FRI'), (2, 'WED')]),
        ),
    ]
