# Generated by Django 4.2 on 2023-04-11 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_alter_businesshour_dayofweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Complete', 'Complete'), ('Failed', 'Failed')], default='Running', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='dayOfWeek',
            field=models.IntegerField(choices=[(0, 'MON'), (4, 'FRI'), (6, 'SUN'), (5, 'SAT'), (1, 'TUE'), (2, 'WED'), (3, 'THU')]),
        ),
    ]
