# Generated by Django 4.2 on 2023-04-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_alter_businesshour_dayofweek_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='csv_report',
            field=models.FileField(default=None, upload_to='csvs/'),
            preserve_default=False,
        ),
    ]
